name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  validate-frontend:
    name: Validate Client Frontend
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
    defaults:
      run:
        working-directory: ./simi-cafe

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
      - run: npm run lint
      - run: npm run build

  validate-admin:
    name: Validate Admin Frontend
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
    defaults:
      run:
        working-directory: ./simi-cafe-admin

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
      - run: npm run lint
      - run: npm run build

  validate-backend:
    name: Validate Backend API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./simi-cafe-backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
      - run: npm run build

  